transport:
  http:
    maxRequestSizeKB: 10024
    requestTimeout: 5s
    server:
      addr: 0.0.0.0:8080
      gracefulTimeout: 5s
      readTimeout: 10s
      readHeaderTimeout: 5s

descriptors:
  kind: remote
  remote:
    timeout: 1m
    reflectionServiceName: grpc.reflection.v1.ServerReflection/ServerReflectionInfo
    exclude:
      - grpc.health.v1.Health
      - grpc.reflection.v1.ServerReflection
      - grpc.reflection.v1alpha.ServerReflection

gateways:
  grpc:
    requestTimeout: 5s 
    client:
      targetAddr: "0.0.0.0:50051"
      requestTimeout: 5s
      tls: true
      tlsSkipverify: true
