name: Go

on: [push]

jobs:
  vulncheck:
    name: vulncheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: "1.22"
          go-package: ./...
